name: Build

on:
  workflow_dispatch:
  pull_request:

env:
  DOTNET_CORE_VERSION: 6.0.x
  PACTS_DIR: "${{ github.workspace }}/pacts"
  PACT_BROKER_BASE_URL: ${{ secrets.PACTFLOW_URL }}
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}
  PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true
  PACT_ENV: stage
  GIT_BRANCH: ${{ github.ref }}
  GIT_COMMIT: ${{ github.sha }}
  # ${{ secrets.STACK_ID }}
  PACTICIPANT: api-client

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: docker pull pactfoundation/pact-cli:latest

      - name: Setup .NET Core SDK ${{ env.DOTNET_CORE_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore Packages
        run: dotnet restore

      - name: Build Application
        run: dotnet build --no-restore

      - name: Run Tests
        run: dotnet test tests

      - name: Publish Pacts
        run: |
          docker run --rm -v ${PACTS_DIR}:/pacts -e PACT_BROKER_BASE_URL -e PACT_BROKER_TOKEN pactfoundation/pact-cli:latest \
            publish /pacts \
            --consumer-app-version ${GIT_COMMIT} \
            --tag ${GIT_BRANCH}

  can-i-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - run: docker pull pactfoundation/pact-cli:latest
      - name: Can I deploy?
        run: |
          docker run --rm -e PACT_BROKER_BASE_URL -e PACT_BROKER_TOKEN pactfoundation/pact-cli:latest \
            broker can-i-deploy \
            --pacticipant ${PACTICIPANT} \
            --version ${GIT_COMMIT} \
            --to ${PACT_ENV}

  deploy:
    runs-on: ubuntu-latest
    needs: can-i-deploy
    steps:
      - uses: actions/checkout@v2
      
      - run: docker pull pactfoundation/pact-cli:latest

      - name: Deploy
        run: echo "Deploy to Stage"

      - name: Record Pact Deployment
        run: |
          docker run --rm -e PACT_BROKER_BASE_URL -e PACT_BROKER_TOKEN pactfoundation/pact-cli:latest \
            broker record-deployment \
            --pacticipant ${PACTICIPANT} \
            --version ${GIT_COMMIT} \
            --environment ${PACT_ENV}

      - name: Add Env Tag to Version
        run: |
          docker run --rm -e PACT_BROKER_BASE_URL -e PACT_BROKER_TOKEN pactfoundation/pact-cli:latest \
            broker create-version-tag \
            --pacticipant ${PACTICIPANT} \
            --version ${GIT_COMMIT} \
            --tag ${PACT_ENV}